// Generated by scripts/gen-visit-map.py. Do not edit by hand.
/** Size of public/makerspace/map-*.svg and the lab inside it, in map units (metres). */
export const VISIT_MAP = {
  width: 3940,
  height: 2654,
  labX: 1926,
  labY: 1330,
} as const;
