// AUTO-GENERATED by scripts/export-board-art.mjs — do not edit by hand.
// Content hash of every board.svg, board-lite.svg, front/back PNG and WebP
// under public/boards (sources and derived rasters/thumbnails). BoardArt
// appends it as ?v= to bust Oxygen's 1-year immutable asset cache when board
// art is regenerated in place.
export const BOARD_ART_VERSION = '5b89f46628ce';
